### ISSUE TITLE
Composer Package Name

### ISSUE THREAD

**Issue by HadesArchitect** [mongrate/mongrate-bundle#28]
https://github.com/mongrate/mongrate-bundle/blob/master/composer.json#L2

Shouldn't it be a "mongrate/mongrate-bundle"?

**Comment by amyboyd** [comment]
The package was published on Composer a while ago (maybe 2 years ago) when I still had the repositories in my personal Github account, so I used `amyboyd/mongrate` everywhere. I moved the repositories to `mongrate` on Github. On Composer it is still `amyboyd/mongrate` for backwards compatibility.

**Comment by amyboyd** [comment]
Here are the packages on Packagist BTW: https://packagist.org/packages/amyboyd/

**Comment by HadesArchitect** [comment]
Of course. But names like 'vendor/package' looks more... solid? 

It looks like Jordi and packagist team STILL doesn't provide a way to smoothly rename a project. That's amazing, the discussion was started 5 years ago... Some things will never change. 

Sorry, I will close the issue.

**Comment by HadesArchitect** [comment]
P.S. Only want to mention what it's possible to rename a project with ~4300 downloads, but nearly impossible to rename a project with 430000 downloads, which you may have later. 

In general they recommend to do it with an abandoning an old project and registering a new one. But that's for you to decide. 

> ![image](https://cloud.githubusercontent.com/assets/1742301/16307020/17a967b0-3960-11e6-856c-807342e8b129.png)
