### ISSUE TITLE
Enable travis.

### ISSUE THREAD

**Issue by BernardoSilva** [mongrate/mongrate-bundle#4]
@amyboyd could you please enable travis for this project?

**Comment by amyboyd** [comment]
Yep, I'll add Travis to this either tomorrow or Sunday.

**Comment by BernardoSilva** [comment]
Can you just activate it? 
I am working on adding tests, I can do the rest, no worry. :) 
Just need you to activate it on travis.

**Comment by BernardoSilva** [comment]
![screen shot 2015-05-29 at 11 30 19](https://cloud.githubusercontent.com/assets/1537510/7880943/27fef812-05f6-11e5-9c3c-e5e10d2cd2fd.png)

Cool :+1: 
Looks like its already activated. 
Thanks
